### ISSUE TITLE
APIRule v2alpha1 path validation and behaviour is wrong

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#1282]
**Description**

According to [proposal](https://github.com/kyma-project/api-gateway/blob/main/docs/contributor/adr/0007-apirule-v2alpha1-api-proposal.md) path can be either exact match or wildcard `*`. 

APIRule v2alpha1 accepts `./*` as valid path. Calling workload results in 404.  

**Expected result**

Accepted path should be either exact match or `*`. Workload does not return 404.

**Actual result**

`./*` is accepted as valid. Workload returns 404

**Steps to reproduce**

```
export NAMESPACE=test
export GATEWAY=kyma-system/kyma-gateway
export DOMAIN_TO_EXPOSE_WORKLOADS={KYMA_DOMAIN}

cat <<EOF | kubectl apply -f -
apiVersion: gateway.kyma-project.io/v2alpha1
kind: APIRule
metadata:
  name: httpbin
  namespace: $NAMESPACE
spec:
  hosts: 
    - httpbin.$DOMAIN_TO_EXPOSE_WORKLOADS
  service:
    name: httpbin
    namespace: $NAMESPACE
    port: 8000
  gateway: $GATEWAY
  rules:
    - path: ./*
      methods: ["GET"]
      noAuth: true
EOF
```

**Troubleshooting**
Tests for validation and first implementation to fix this can be found in the PR https://github.com/kyma-project/api-gateway/pull/1285. 

**PR**
- https://github.com/kyma-project/api-gateway/pull/1285
