### ISSUE TITLE
conversion-webhook failed to convert {"request": "xxx", "error": "json: cannot unmarshal object into Go value of type string"}

### ISSUE THREAD

**Issue by tehret77** [kyma-project/api-gateway#1606]
**Description**

We noticed in the logs from the api-gateway-manager pod lots of log lines like these:

```
2025-01-10T14:00:51Z	ERROR	conversion-webhook	failed to convert	{"request": "4d6072ce-e31d-49fa-b936-8baeeb3beb07", "error": "json: cannot unmarshal object into Go value of type string"}
sigs.k8s.io/controller-runtime/pkg/webhook/conversion.(*webhook).ServeHTTP
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/webhook/conversion/conversion.go:74
sigs.k8s.io/controller-runtime/pkg/webhook/internal/metrics.InstrumentedHook.InstrumentHandlerInFlight.func1
	/go/pkg/mod/github.com/prometheus/client_golang@v1.20.5/prometheus/promhttp/instrument_server.go:60
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2220
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1
	/go/pkg/mod/github.com/prometheus/client_golang@v1.20.5/prometheus/promhttp/instrument_server.go:147
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2220
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2
	/go/pkg/mod/github.com/prometheus/client_golang@v1.20.5/prometheus/promhttp/instrument_server.go:109
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2220
net/http.(*ServeMux).ServeHTTP
	/usr/local/go/src/net/http/server.go:2747
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:3210
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:2092
```

We upgraded the api-gateway module from v2.7.0 to v.2.10.2 and saw this messages already there.
These error messages are related to the CRD conversion strategy:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: api-gateway-operator-default
    app.kubernetes.io/name: api-gateway-operator
    app.kubernetes.io/part-of: api-gateway
    app.kubernetes.io/version: 2.10.2
    kyma-project.io/module: api-gateway
  name: apirules.gateway.kyma-project.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: api-gateway-webhook-service
          namespace: kyma-system
          path: /convert
          port: 9443
      conversionReviewVersions:
      - v1beta1
      - v2alpha1
  group: gateway.kyma-project.io
[...]
```

Can you give us a hint what could be wrong with out apirules (v1beta1) that this error is produced?

**Expected result**

no such error messages appear in the logs.

**Actual result**

a lot of error messages appear in the logs.

**Steps to reproduce**

2 examples of APIrules we have in use:
```
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  annotations:
    meta.helm.sh/release-name: some-service-name
    meta.helm.sh/release-namespace: some-namespace
  creationTimestamp: "2024-12-09T16:36:04Z"
  finalizers:
  - gateway.kyma-project.io/subresources
  generation: 1
  labels:
    app: some-service-name
    app.kubernetes.io/instance: some-service-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: some-service-name
    app.kubernetes.io/version: 20250109.22624ca.235
    helm.toolkit.fluxcd.io/name: some-service-name
    helm.toolkit.fluxcd.io/namespace: some-namespace
    version: 20250109.22624ca.235
  name: some-service-name-api
  namespace: some-namespace
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: some-service-name-api.some.domain.com
  rules:
  - accessStrategies:
    - config:
        introspection_url: http://ias-oauth-helper.ias-ooath.svc.cluster.local:80/jwt-introspection
        required_scope:
        - service-name.read
        scope_strategy: exact
      handler: oauth2_introspection
    methods:
    - POST
    mutators:
    - config:
        headers:
          X-ClientId: '{{ print .Subject }}'
      handler: header
    path: /.*
  service:
    name: some-service-name
    namespace: some-namespace
    port: 8080
status:
  APIRuleStatus:
    code: OK
  accessRuleStatus:
    code: OK
  lastProcessedTime: "2025-01-10T15:16:12Z"
  observedGeneration: 1
  virtualServiceStatus:
    code: OK
``` 

```
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  annotations:
    meta.helm.sh/release-name: service-tool
    meta.helm.sh/release-namespace: service-tool
  creationTimestamp: "2024-12-02T11:58:49Z"
  finalizers:
  - gateway.kyma-project.io/subresources
  generation: 1
  labels:
    app: service-tool
    app.kubernetes.io/instance: service-tool
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: service-tool
    app.kubernetes.io/version: v202409041141.9d251c6
    version: v202409041141.9d251c6
  name: service-tool
  namespace: service-tool
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: service-tool.some.domain.com
  rules:
  - accessStrategies:
    - config:
        jwks_urls:
        - https://IAS.tenant.com/oauth2/certs
        trusted_issuers:
        - https://IAS.tenant.com/
      handler: jwt
    methods:
    - GET
    path: /scopes/.*
  service:
    name: service-tool
    namespace: service-tool
    port: 80
status:
  APIRuleStatus:
    code: OK
  accessRuleStatus:
    code: OK
  lastProcessedTime: "2025-01-10T16:16:03Z"
  observedGeneration: 1
  virtualServiceStatus:
    code: OK
```
**Troubleshooting**

**DoD [Developer & Reviewer]**

- [ ] Provide unit and integration tests.
- [ ] Provide documentation.
- [ ] Verify if the solution works for both open-source Kyma and SAP BTP, Kyma runtime.
- [ ] If you changed the resource limits, explain why it was needed.
- [ ] Verify that your contributions don't decrease code coverage. If they do, explain why this is the case.
- [ ] Add release notes.
