### ISSUE TITLE
bug: RateLimit: fail when fill_interval is set above `60s`

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/api-gateway#1626]
/kind bug
/area api-gateway

**Description**

When RateLimit is deployed, Istiod returns an error if `fill_interval` contains values below or above seconds.
```
2025-01-20T10:50:32.427568Z     warn    delta   ADS:LDS: ACK ERROR httpbin.test-1 Internal:Error adding/updating listener(s) virtualInbound: Unable to parse JSON as proto (INVALID_ARGUMENT: invalid JSON in   envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit @ descriptors[0].token_bucket.fill_interval: message google.protobuf.Duration, near   1:514 (offset 513): duration must end   with  a single 's'): {...}
```

**Expected result**
RateLimit configuration gets applied correctly.

**Steps to reproduce**

RateLimit CR
```yaml
apiVersion: gateway.kyma-project.io/v1alpha1
kind: RateLimit
metadata:
  labels:
    app: httpbin
  name: ratelimit-path-sample
  namespace: test
spec:
  selectorLabels:
    app: httpbin
  enableResponseHeaders: true
  local:
    defaultBucket:
      maxTokens: 100
      tokensPerFill: 50
      fillInterval: 30s
    buckets:
      - path: /ip
        bucket:
          maxTokens: 1
          tokensPerFill: 1
          fillInterval: 60m
```

**Troubleshooting**
I believe we can't rely on go's default duration parse. All durations need to be converted to seconds. When EnvoyFilter contains `ms`, I got an error:
```
2025-01-20T13:13:42.256815Z     warn    delta   ADS:LDS: ACK ERROR httpbin.test-17 Internal:Error adding/updating listener(s) virtualInbound: Proto constraint validation failed (LocalRateLimitValidationError.Descriptors[0]: embedded message failed validation | caused by LocalRateLimitDescriptorValidationError.TokenBucket: embedded message failed validation | caused by TokenBucketValidationError.FillInterval: value must be greater than 0s): stat_prefix: "rate_limit"
```

That means we can only use seconds.
