### ISSUE TITLE
bug: ratelimit: validation error `path or headers must be set` when both path and headers fields are present in CR

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/api-gateway#1629]
When the following rate limit CR is applied the the validation returns an error:
```
The RateLimit "ratelimit-header-sample" is invalid: spec.local.buckets[0]: Invalid value: "object": path or headers must be set
```

```yaml
apiVersion: gateway.kyma-project.io/v1alpha1
kind: RateLimit
metadata:
  labels:
    app: httpbin
  name: ratelimit-header-sample
  namespace: test
spec:
  selectorLabels:
    app: httpbin
  enableResponseHeaders: true
  local:
    defaultBucket:
      maxTokens: 1
      tokensPerFill: 1
      fillInterval: 30s
    buckets:
      - headers:
          X-Rate-Limited: "true"
        path: /headers
        bucket:
          maxTokens: 10
          tokensPerFill: 5
          fillInterval: 30s
```

This is incorrect behaviour, because this particular bucket example is projected as valid in ADR. See: https://github.com/kyma-project/api-gateway/blob/main/docs/contributor/adr/0011-rate-limit.md#usage-example

The error is in validation rule in https://github.com/kyma-project/api-gateway/blob/a936d168d69da0ab87761c35b58c1a3769015cac/apis/gateway/ratelimit/v1alpha1/ratelimit_types.go#L30. It only allows either `path` or `headers` to be defined.

/kind bug
/area api-gateway
