### ISSUE TITLE
Applying v2alpha1 APIRule blocks in-cluster communication to the target

### ISSUE THREAD

**Issue by barchw** [kyma-project/api-gateway#1632]
**Description**

Applying v2alpha1 APIRule blocks in-cluster communication to the target, as an AP (AuthorizationPolicy) (action type: ALLOW) is applied in all cases. As logic behind [AP](https://istio.io/latest/docs/reference/config/security/authorization-policy/) blocks all traffic except for a match to the ALLOW AuthorizationPolicy, the internal traffic is blocked unless it is allowed explicitly by a different AP of type ALLOW.

**Expected result**
Application of v2alpha1 APIRule to a workload should not block in-cluster traffic targeting the workload.

**Actual result**
Any traffic other than incoming from istio-ingressgateway and matching the APIRule restrictions is blocked.

**Steps to reproduce**
1. APIGateway module installed
  ```yaml
  kubectl apply -f https://github.com/kyma-project/istio/releases/latest/download/istio-manager.yaml
  kubectl apply -f https://github.com/kyma-project/istio/releases/latest/download/istio-default-cr.yaml

  kubectl apply -f https://github.com/kyma-project/api-gateway/releases/latest/download/api-gateway-manager.yaml
  kubectl apply -f https://github.com/kyma-project/api-gateway/releases/latest/download/apigateway-default-cr.yaml
  ```
2. A target workload present (and Istio injected)
  ```yaml
  export NAMESPACE_NAME=sidecar-enabled
  kubectl create ns ${NAMESPACE_NAME}
  kubectl label namespace $NAMESPACE_NAME istio-injection=enabled --overwrite
  kubectl -n ${NAMESPACE_NAME} apply -f https://raw.githubusercontent.com/istio/istio/master/samples/httpbin/httpbin.yaml
  ```
3. An APIRule created, targeting the workload, handler is irrelevant (can be e.g. noAuth)
  ```yaml
  apiVersion: gateway.kyma-project.io/v2alpha1
  kind: APIRule
  metadata:
    name: "httpbin"
    namespace: sidecar-enabled
  spec:
    gateway: "kyma-system/kyma-gateway"
    hosts:
      - "httpbin"
    service:
      name: httpbin
      port: 8000
    rules:
      - path: /anything/{**}
        methods: ["GET"]
        noAuth: true
  ```
4. Internal traffic to the httpbin pod will be blocked

**PR**
- https://github.com/kyma-project/api-gateway/pull/1666

**DoD [Developer & Reviewer]**

- [ ] Provide unit and integration tests.
- [ ] Provide documentation.
- [ ] Verify if the solution works for both open-source Kyma and SAP BTP, Kyma runtime.
- [ ] If you changed the resource limits, explain why it was needed.
- [ ] Verify that your contributions don't decrease code coverage. If they do, explain why this is the case.
- [ ] Add release notes.

**Comment by I551317** [comment]
> We discussed it during the refinement:
> 
> * let's add AP that allows internal traffic except Ingress controller, like:
> 
> ```
> apiVersion: security.istio.io/v1
> kind: AuthorizationPolicy
> metadata:
>   name: allow-internal
>   namespace: sidecar-enabled
> spec:
>   selector:
>     matchLabels:
>       app: httpbin
>   action: ALLOW
>   rules:
>   - from:
>     - source:
>         notPrincipals: ["cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"]
> ```

Out of my curiosity. If you are about to extend current implementation by adding a new AP with "notPrincipal" set, wouldn't it be simpler and cleaner just to remove the prior AuthorizationPolicy (with ALLOW for that Principal)? Wouldn't that be the same as no having AP at all? Are there any pros of such an approach that I'm missing?

**Comment by barchw** [comment]
@I551317 This unfortunately would not have the same outcome for all cases.
If there would be no AP created for the `noAuth` policy, creating any other AP that would target the same workload (for example to expose some particular path using JWT strategy) would end up blocking the traffic incoming to the path exposed with `noAuth`.

For example imagine the following configuration:

```yaml
  rules:
    - path: /headers
      methods: ["GET"]
      jwt:      
        authentications:
        - issuer: https://example.com
          jwksUri: https://example.com
    - path: /anything/{**}
      methods: ["GET"]
      noAuth: true
```

In this case, APIRule would create an AP for JWT exposed `/headers` path, that would block access to the noAuth `/anything/{**}` path as a side-effect (keeping in mind, that the policies are evaluated per workload, not path). This is because if any `ALLOW` type AP exists, the request needs to match at least one.
> [Istio AP docs](https://istio.io/latest/docs/reference/config/security/authorization-policy/): 
> 3. If there are no ALLOW policies for the workload, allow the request.
> 4. If any of the ALLOW policies match the request, allow the request.
> 5. Deny the request.

The case where only a `noAuth` path exists is a special, as it technically does not require an AP when there is nothing else targeting this workload. However, for the sake of a uniform solution with different scenarios (like the above JWT scenario) we presume it is better to explicitly create an AP for the `noAuth` path every time.
