### ISSUE TITLE
feat: ratelimit: implement local rate limiting for gateway

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/api-gateway#1812]
RateLimit CR currently does not support local rate limiting for istio-ingressgateway. It's a missing functionality.

This feature is described in ADR, though without examples.
>The RateLimit CR allows to configure rate limiting on sidecar proxies and Istio Ingress Gateways.
The workloads that should be rate limited are selected by the required selectorLabels field. The selectorLabels field contains a map of labels that indicate a specific set of Pods on which the configuration should be applied.
The selector labels are restricted to the namespace in which the RateLimit CR is present. Due to restrictions by Istio module, the Istio Ingress Gateway can only be deployed to the istio-system namespace and the user must create a RateLimit CR in the istio-system namespace to apply rate limits to the Istio Ingress Gateway.
>
>To create a valid EnvoyFilter from the RateLimit CR, the [PatchContext](https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-PatchContext) must be configured appropriately. The PatchContext must be set to SIDECAR_INBOUND for sidecar proxies to ensure that only ingress traffic is rate limited. For Istio Ingress Gateway rate limiting, the PatchContext must be set to GATEWAY.

The feature needs to be declarative. The configuration that the rate limit is for ingress gateway needs to be reflected in a resource. Gateway-type RateLimit CRs *must* be deployed in istio-system and gateway-type RateLimits should *not* reconcile and error out, if deployed outside of istio-system.

example of gateway ratelimit:
```yaml
apiVersion: gateway.kyma-project.io/v1alpha1
kind: RateLimit
metadata:
  labels:
    app: ig-ratelimit
    namespace: istio-system
  name: ratelimit-path-sample
  namespace: test
spec:
  selectorLabels:
    app: istio-ingressgateway # or anything pointing to istio-ingressgateway
  type: GATEWAY # or SIDECAR_INBOUND, default SIDECAR_INBOUND
  enableResponseHeaders: true
  local:
    defaultBucket:
      maxTokens: 5
      tokensPerFill: 5
      fillInterval: 60s
    buckets:
      - path: /
        bucket:
          maxTokens: 10
          tokensPerFill: 5
          fillInterval: 60m
```
