### ISSUE TITLE
APIRule does not support access to paths that can possibly conflict

### ISSUE THREAD

**Issue by barchw** [kyma-project/api-gateway#1817]
**Description**

There is no way to configure an APIRule that has the following configuration, as the path conflict validation prevents it:

```yaml
  rules:
    - path: /anything
      methods: [ "GET" ]
      noAuth: true
    - path: /*
      methods:
        - "GET"
        - "POST"
        - "DELETE"
        - "PUT"
      jwt:
        authentications:
```

In VirtualService this is supported out of the box, as the match happens on the first matching rule in the array:
```yaml
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: httpbin
  namespace: sidecar-enabled
spec:
  gateways:
  - kyma-system/kyma-gateway
  hosts:
  - httpbin.example.com
  http:
  - match:
    - method:
        regex: ^(GET|POST|PUT|DELETE)$
      uri:
        regex: ^/anything/([A-Za-z0-9-._~!$&'()*+,;=:@/]|%[0-9a-fA-F]{2})*$
    route:
    - destination:
        host: httpbin.sidecar-enabled.svc.cluster.local
        port:
          number: 8000
      weight: 100
    timeout: 180s
  - match:
    - method:
        regex: ^(GET|POST|PUT|DELETE)$
      uri:
        regex: ^/([A-Za-z0-9-._~!$&'()*+,;=:@/]|%[0-9a-fA-F]{2})*$
    route:
    - destination:
        host: httpbin.sidecar-enabled.svc.cluster.local
        port:
          number: 8000
      weight: 100
    timeout: 180s
```

Above would match on the first array entry on `/anything`, and the second on any other path.

From AuthorizationPolicies this is possible as well by configuring the `notPaths` parameter, preventing the conflict.

```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: httpbin-jwt
  namespace: sidecar-enabled
spec:
  rules:
  - from:
    - source:
        requestPrincipals:
        - http://mock-oauth2-server.mock-oauth2.svc.cluster.local/*
    to:
    - operation:
        methods:
        - GET
        - POST
        - PUT
        - DELETE
        paths:
        - /anything/{**}
  selector:
    matchLabels:
      app: httpbin
```

```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: httpbin-noauth
  namespace: sidecar-enabled
spec:
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account
    to:
    - operation:
        methods:
        - GET
        - POST
        - PUT
        - DELETE
        notPaths:
        - /anything/{**}
        paths:
        - /{**}
  selector:
    matchLabels:
      app: httpbin
```

To achieve the above to possible solutions could be:
- If conflict happens, generate the `notPaths` param on the path that encapsulates the other
- Add an additional API field that would allow setting `notPaths` explicitly.

**Reasons**

Support for handler overrides.

**Attachments**
