### ISSUE TITLE
RBAC access denied on path containing *

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#1839]
**Description**

Having APIRule v2 exposing a workload using {**} operator gives RBAC access denied error trying to access path containing *. Seems like Istio resources apirule controller creates are valid. URL and path validation seem to be valid too. 

TODO:
- [ ] consult @TorstenD-SAP 
- [ ] check with Envoy why * is excluded
- [ ] create Envoy issue if needed
- [ ] propose workaround

**Expected result**

exposed workload is accessible

**Actual result**

403

**Steps to reproduce**

1. expose httpbin using /{**} and noAuth handler
2. call httpbin  endpoint containing *

**Troubleshooting**
https://github.com/envoyproxy/envoy/blob/35d358ed87692f4a1731ce81b120b9b159db1092/source/extensions/path/uri_template_lib/uri_template_internal.cc#L45

**Comment by barchw** [comment]
Possible workaround involves creating an EnvoyFilter that would allow the path using regex. However, implementing this in the API Gateway controller logic ATM would be tremendous effort as it would require to replace the `AuthorizationPolicy` logic with EnvoyFilter logic.

Example below allowing to expose the regex path `/anything/.*/abc`
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: rbac-allow-abc
  namespace: sidecar-enabled
spec:
  workloadSelector:
    labels:
      app: httpbin
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND  # Use GATEWAY if targeting ingress
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: 'envoy.filters.http.rbac'
          typed_config:
            "@type": 'type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC'
            rules:
              action: ALLOW
              policies:
                "allow-path-abc":
                  principals:
                  - and_ids:
                      ids:
                      - or_ids:
                          ids:
                          - authenticated:
                              principal_name:
                                exact: "spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"
                  permissions:
                    - and_rules:
                        rules:
                        - url_path:
                            path:
                              # exact: /anything
                              safe_regex: 
                                regex: "/anything/.*/abc"
```
