### ISSUE TITLE
Changing JWT handler through config map not working reliable

### ISSUE THREAD

**Issue by triffer** [kyma-project/api-gateway#274]
AC:
- [x] Test behaviour on Azure

**Description**

When changing the JWT handler through the config map `api-gateway-config` the reconciler won't pick up the newly changed handler. Only a restart of the controller pod will make the reconciler use the updated handler.
This means a change in the config map no longer triggers the reconciliation.

It seems that this is related to the change in https://github.com/kyma-project/api-gateway/pull/193.

**PR**
- https://github.com/kyma-project/api-gateway/pull/275

**Expected result**

Updating the `api-gateway-config` config map will change the configured handler without the need of restarting the pod.

**Actual result**

After updating the `api-gateway-config` config map the old handler is still used for reconciliation.

**Steps to reproduce**

- Set api-gateway-config CM to ory and deploy api-gateway-controller 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: kyma-system
data:
  api-gateway-config: 'jwtHandler: ory'
```

- Create APIRule with Ory-based jwt config, this will create APIRule with Status OK
```
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: my-rule
  namespace: kyma-system
spec:
  gateway: kyma-system/kyma-gateway
  host: host.local.kyma.dev
  service:
    name: service
    port: 8000
  rules:
    - path: /headers
      methods: [ "GET" ]
      accessStrategies:
        - handler: jwt
          config:
            jwks_urls:
              - https://some.url.com/oauth2/certs
```

- Change api-gateway-config CM to istio 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: kyma-system
data:
  api-gateway-config: 'jwtHandler: istio'
```

- Update APIRule to Istio-based jwt config will result in APIRule in Error state with error `Validation error: Attribute ".spec.rules[0].accessStrategies[0].config.authentications": Configuration for authentications is not supported with Ory handler`
```
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: my-rule
  namespace: kyma-system
spec:
  gateway: kyma-system/kyma-gateway
  host: host.local.kyma.dev
  service:
    name: service
    port: 8000
  rules:
    - path: /headers
      methods: [ "GET" ]
      accessStrategies:
        - handler: jwt
          config:
            authentications:
              - issuer: https://some.url.com
                jwksUri: https://some.url.com/oauth2/certs
```
- Restarting the api-controller pod will bring the APIRule into OK state

**Troubleshooting**
