### ISSUE TITLE
Support for wildcard host/multiple hosts

### ISSUE THREAD

**Issue by pbusko** [kyma-project/api-gateway#419]
**Description**

At the moment, each `APIRule` object is bound to single external URL, however the underlying `VirtualService` object is capable of serving multiple hosts at the same time, or use regex matchers for the `Host` header.

Example with regex matcher (will match `a-http-echo.my.domain.com`, `b-http-echo.my.domain.com` etc.):
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: http-echo
  namespace: http-echo
spec:
  gateways:
    - kyma-system/kyma-gateway
  hosts:
    - '*'
  http:
    - corsPolicy:
        allowHeaders:
          - Authorization
          - Content-Type
          - '*'
        allowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
        allowOrigins:
          - regex: .*
      match:
        - uri:
            regex: /.*
          headers:
            Host:
              regex: ^(.*)-http-echo\.my\.domain\.com$
      route:
        - weight: 100
          destination:
            host: http-echo.http-echo.svc.cluster.local
```

Example with multiple hosts:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: http-echo
  namespace: http-echo
spec:
  gateways:
    - kyma-system/kyma-gateway
  hosts:
    - 'a-http-echo.my.domain.com'
    - 'b-http-echo.my.domain.com'
  http:
    - corsPolicy:
        allowHeaders:
          - Authorization
          - Content-Type
          - '*'
        allowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
        allowOrigins:
          - regex: .*
      match:
        - uri:
            regex: /.*
      route:
        - weight: 100
          destination:
            host: http-echo.http-echo.svc.cluster.local
```

Would be very helpful to have support from `APIRule` for such use cases, by either introducing new `spec.hosts` array, or making `spec.host` regex capable by switching to the `Host` header regex matcher (or both).

**Reasons**

These features would greatly improve Kyma support for [Multitenant CAP applications](https://cap.cloud.sap/docs/guides/deployment/as-saas), which are using SaaS Registry Service.
At the moment there's no easy way to handle multitenant URLs on Kyma.

**DoD:**
- [ ] provide documentation
- [ ] release notes and What's New updates for Kyma customers
- [ ] provide unit tests
- [ ] provide integration tests
- [ ] test on production-like environment
- [ ] verify resource limits
- [ ] followup issue
- [ ] create release and bump in kyma
- [ ] PR reviewer will verify code coverage and evaluate if it is acceptable

**Attachments**
