### ISSUE TITLE
Support mutators in UI

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#612]
**Description**

APIRule with mutators created via UI results in 500 returned during a call to workload.

**Expected result**

Workload exposed with apirule with mutators is accessible

**Actual result**

Workload exposed with apirule with mutators returns 500

**Steps to reproduce**

Create APIRule with mutator via UI

**Troubleshooting**
<img width="1308" alt="Screenshot 2023-10-11 at 13 25 17" src="https://github.com/kyma-project/api-gateway/assets/13993883/71695776-aaf0-43ed-85b2-18b5a63f88d4">

```
cat <<EOF | kubectl apply -f -
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: httpbin
  namespace: default
spec:
  host: httpbin.kyma.local.dev
  service:
    name: httpbin
    namespace: default
    port: 8000
  gateway: kyma-system/kyma-gateway
  rules:
    - path: /.*
      methods: ["GET"]
      accessStrategies:
        - handler: noop
      mutators:
        - handler: header
          config:
            headers:
              x-forwarded-host: tratata.kyma.local.dev
EOF
```

**PR**
- [ ] https://github.com/kyma-project/api-gateway/pull/895
