### ISSUE TITLE
Error when "corsPolicy" spec is added

### ISSUE THREAD

**Issue by tonymathew17sap** [kyma-project/api-gateway#814]
**Description**
As per Kyma documentation [here](https://kyma-project.io/#/api-gateway/user/custom-resources/apirule/04-10-apirule-custom-resource:~:text=the%20Istio%20Gateway.-,corsPolicy,-NO), corsPolicy is supported. However, I'm getting the following error:
`strict decoding error: unknown field "spec.corsPolicy"`

**Expected result**
'corsPolicy' spec should be supported

**Actual result**
Getting the error: 
`strict decoding error: unknown field "spec.corsPolicy"`

**Steps to reproduce**
1. Use the following K8s file:
```
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  labels:
    app: approuter
  name: approuter
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: vehicle-service-approuter.c7faf5c.kyma.ondemand.com
  corsPolicy:
    allowCredentials: 'true'
  rules:
    - path: /.*
      methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
      service:
        name: approuter
        port: 5000
      accessStrategies:
        - handler: noop
```
Getting the error:
`strict decoding error: unknown field "spec.corsPolicy"`

**Troubleshooting**
