### ISSUE TITLE
Validation of noop access strategy does not match the documentation

### ISSUE THREAD

**Issue by triffer** [kyma-project/api-gateway#866]
**Description**

In our [APIRule docs](https://github.com/kyma-project/api-gateway/blob/main/docs/user/custom-resources/apirule/04-10-apirule-custom-resource.md) we mention:

> Access strategies noop or allow cannot be used with any other access strategy on the same spec.rules.path.

While this is true for allow, that's not the case for noop .

We don't have any validation in place and it's possible to configure noop and jwt handler for the same path. In this case access is always possible.

**Expected result**
When noop and another access strategy is on the same path, the validation will fail with message
```
noop access strategy is not allowed in combination with other access strategies
```

**Actual result**
`noop` handler can be added with other handlers on the same path and changes the behaviour, e.g. by allowing access to JWT secured path.

**Steps to reproduce**
- Deploy a workload
- Secure workload with APIRule that exposes `GET`and `POST` on path `/anything` with jwt and noop handler.
```
kubectl apply -f - <<EOF
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: httpbin-rule
  namespace: default
  labels:
    app: httpbin
spec:
  gateway: kyma-system/kyma-gateway
  host: httpbin
  service:
    name: httpbin
    port: 8000
  rules:
    - path: /anything
      methods: [ "GET", "POST"]
      mutators: [ ]
      accessStrategies:
        - handler: jwt
          config:
            trusted_issuers:
              - https://kymagoattest.accounts400.ondemand.com
            jwks_urls:
              - https://kymagoattest.accounts400.ondemand.com/oauth2/certs
        - handler: noop
EOF
```
- APIRule in status OK
- Access to GET on `/anything` is not restricted

**Troubleshooting**
