### ISSUE TITLE
Host link in APIRule in UI broken 

### ISSUE THREAD

**Issue by triffer** [kyma-project/api-gateway#870]
**Description**

When you add an APIRule that has only a short "host" defined, e.g. `host: httpbin` the host in the APIRule UI is broken.
The host is incorrect in the list and details view.
![image](https://github.com/kyma-project/api-gateway/assets/11753933/c1e27bc5-8d36-4bc5-9e32-cdb6d37f647b)
![image](https://github.com/kyma-project/api-gateway/assets/11753933/526ec57b-a7a9-4a47-aff3-c8d4a658f008)

**Expected result**
The host link in the APIRule list and details is valid and doesn't contain `null`.

**Actual result**
The APIRule host link is broken.

**Steps to reproduce**

- Apply APIRule without full host name
```
kubectl apply -f - <<EOF
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: httpbin-rule
  namespace: default
  labels:
    app: httpbin
spec:
  gateway: kyma-system/kyma-gateway
  host: httpbin
  service:
    name: httpbin
    port: 8000
  rules:
    - path: /anything
      methods: [ "GET", "POST"]
      mutators: [ ]
      accessStrategies:
        - handler: no_auth
EOF
```
- Check APIRules list and details of the APIRule

**Troubleshooting**
