### ISSUE TITLE
Allow exposing workloads on rewritable path

### ISSUE THREAD

**Issue by barchw** [kyma-project/api-gateway#98]
**Description**
As both Istio and Ory support path rewrite in some capacity (Istio has `rewrite` parameter in VirtualService http match and Ory Rules support `strip_path` in upstream) it would be possible to support exposing workloads with paths different than exposed outside

**Reasons**

- Other providers of APIGateway are already supporting this type of configuration
- This would allow exposing of workloads where path collision would occur (such as two httpbin deployments) without using virtual hosts

**Sample configuration**

When exposing a service with APIRule in matter similar to this one:

```yaml
- path: /httpbin/headers
  stripPath: /httpbin
  service:
     name: httpbin
     port: 8000
```

The generated resources for VirtualService and Ory Rule would take this form:

```yaml
# Virtual Service on ALLOW type of APIRule
#[...]
http:
  - name: "reviews-v2-routes"
    match:
    - uri:
        prefix: "/httpbin/headers"
    rewrite:
      uri: "/headers"
#[...]
```

```yaml
# Rule on secured type of APIRules
#[...]
upstream: {{ Service }}/httpbin/headers
stripPath: /httpbin
#[...]
```

**DoD:**
- [ ] provide documentation
- [ ] publish release notes and _What's New_ updates for Kyma customers
- [ ] provide unit tests
- [ ] test on SKR
- [ ] verify [Get started guides](https://kyma-project.io/docs/kyma/latest/02-get-started/) 
- [ ] verify resource limits
- [ ] followup issue
- [ ] create release and bump in kyma
